# we can fullscreen ourselves because of the usage of a tiling window manager
#fullscreen=yes

#audio
volume=100
volume-max=150

#sub/audio lang
slang=enm,english full,en,eng,enUS
alang=ja,jp,jpn,en,eng
sub-auto=fuzzy
sub-font='Trebuchet MS'
sub-bold=yes # Set the font to bold.
#sub-font-size=55 # Set default subtitle size if not specified.



#video
save-position-on-quit
video-sync=display-resample
interpolation
tscale=oversample

#screenshots
--screenshot-directory='C:\Users\hotsno\Google Drive\Stuff\Screenshots\Anime\UNSORTED'
--screenshot-jpeg-quality=99
--screenshot-template="%F %whh%wMm%wSs"

# For powerful PC
profile=gpu-hq
vo=gpu
gpu-api=vulkan 

scale=ewa_lanczossharp
dscale=mitchell
cscale=spline36 # alternatively ewa_lanczossoft depending on preference

glsl-shader="~/.config/mpv/shaders/SSimSuperRes.glsl" # Set B C parameter to Robidoux.
scale=ewa_lanczossharp
dscale=mitchell
cscale=spline64
