#! /bin/sh

$HOME/.config/bspwm/devices.sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8  

bspc config border_width        1
bspc config window_gap          25

bspc config top_padding 	0 
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# bspc config focus_follows_pointer true
bspc monitor HDMI-1 -d draw social music he 
bspc monitor eDP-1 -d bash www game work music com watch rec 
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
# since i draw alot

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a osu! state=fullscreen
bspc rule -a Steam state=floating
bspc rule -a "origin.exe" state=floating
bspc rule -a "zoom " state=floating
bspc rule -a "robloxplayerlauncher.exe" state=floating
bspc rule -a "robloxplayerbeta.exe" desktop='^3' follow=on focus=on 
bspc rule -a "telegram-desktop" state=floating
bspc rule -a discord desktop='^6' 
bspc rule -a "microsoft teams - preview" desktop='^4'
bspc rule -a firefox desktop='^2' follow=on focus=on

picom &


xsetroot -cursor_name left_ptr &

$HOME/.config/polybar/launch.sh
nm-applet &
blueman-applet &
dunst &
setxkbmap -option grp:alt_shift_toggle us,ar &

feh --bg-scale ~/donttouch/background.jpg &
wal -i ~/donttouch/background.jpg &

# Autostart
startup_lock_file=/tmp/bspwm-startup.lock
if [ ! -f $startup_lock_file ]; then
  echo "dummy" > $startup_lock_file
  keepassxc & dropbox start & flameshot
fi
