foreground   #dcc5da
background   #100011
cursor       #dcc5da

color0       #100011
color8       #9a8998
color1       #6F9CEA
color9       #6F9CEA
color2       #AD8ABB
color10      #AD8ABB
color3       #E199B3
color11      #E199B3
color4       #959CDA
color12      #959CDA
color5       #B19BD0
color13      #B19BD0
color6       #91A7E6
color14      #91A7E6
color7       #dcc5da
color15      #dcc5da

# no bells. Ever.
enable_audio_bell no
bell_on_tab no


# don't draw extra borders, but fade the inactive text a bit
active_border_color none
inactive_text_alpha 0.6

confirm_os_window_close 0

font_family Hack Nerd Font Bold

font_size 12

cursor_shape underline

cursor_blink_interval -1


